- name: os variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_os_family | lower }}.yml'
  tags:
    - root

- name: install packages
  when: root_install_package | default(True)
  loop:
    - git
  package:
    name: '{{ item }}'
    state: present
  tags:
    - root

- name: update password
  when: root_password != ""
  user:
    name: root
    password: '{{ root_password }}'
    update_password: always
  tags:
    - root

- name: enforce shell
  when: root_shell != ""
  user:
    name: root
    shell: '{{ root_shell }}'
  tags:
    - root

- name: clone homeshick
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: '{{ root_home_path }}/.homesick/repos/homeshick'
  tags:
    - root

- name: clone castles
  with_items: '{{ root_castles }}'
  when: root_castles|default(None) != None
  git:
    repo: 'https://github.com/{{ item.name | default(item) }}.git'
    dest: '{{ root_home_path }}/.homesick/repos/{{ (item.name | default(item)) | basename }}'
    force: '{{ item.force | default(root_castles_force) }}'
  tags:
    - root

- name: link castles
  with_items: '{{ root_castles }}'
  when: root_castles|default(None) != None
  command: '{{ root_home_path }}/.homesick/repos/homeshick/bin/homeshick -f -b -q link {{ item | basename }}'
  changed_when: False
  tags:
    - root

- name: write sshkeys
  when: root_sshkeys|default(None) != None
  authorized_key:
    user: root
    key: '{{ root_sshkeys }}'
    path: '{{ root_home_path }}/.ssh/authorized_keys'
    exclusive: True
    state: present
  tags:
    - root
