# Standards: 1.2
---
- name: Install required packages
  loop:
    - git
  package:
    name: "{{ item }}"
    state: present
  tags:
    - root

- name: Update root password
  when: root_password | default(False)
  user:
    name: root
    password: "{{ root_password }}"
    update_password: always
  tags:
    - root

- name: Enforce root shell
  when: root_shell | default(False)
  user:
    name: root
    shell: "{{ root_shell }}"
  tags:
    - root

- name: Install ohmyzsh repo
  when: root_ohmyzsh | default(False)
  no_log: True
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /root/.oh-my-zsh
  tags:
    - root

- name: Install bashit repo
  when: root_bashit | default(False)
  no_log: True
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: /root/.bash_it
  tags:
    - root

- name: Clone homeshick base
  no_log: True
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: /root/.homesick/repos/homeshick
  tags:
    - root

- name: Clone homeshick castles
  loop: "{{ root_castles }}"
  loop_control:
    label: "{{ item.name | default(item) }}"
  when: root_castles | default(False)
  git:
    repo: "https://github.com/{{ item.name | default(item) }}.git"
    dest: "/root/.homesick/repos/{{ (item.name | default(item)) | basename }}"
    force: "{{ item.force | default(root_castles_force) }}"
  tags:
    - root

- name: Link homeshick castles
  loop: "{{ root_castles }}"
  loop_control:
    label: "{{ item.name | default(item) }}"
  when: root_castles | default(False)
  command: "/root/.homesick/repos/homeshick/bin/homeshick -f -b -q link {{ item | basename }}"
  changed_when: False
  tags:
    - root

- name: Write authorized keys
  when: root_sshkeys | default(False)
  authorized_key:
    user: root
    key: "{{ root_sshkeys | join('\n') }}"
    path: /root/.ssh/authorized_keys
    exclusive: True
    state: present
  tags:
    - root

...
