- name: install packages
  with_items:
    - git
  package:
    name: '{{ item }}'
    state: present
  tags:
    - root

- name: clone homeshick
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: /root/.homesick/repos/homeshick
  tags:
    - root

- name: clone castles
  with_items: '{{ root_castles }}'
  when: root_castles|default(None) != None
  git:
    repo: 'https://github.com/{{ item.name | default(item) }}.git'
    dest: '/root/.homesick/repos/{{ (item.name | default(item)) | basename }}'
    force: '{{ item.force | default(root_castles_force) }}'
  tags:
    - root

- name: link castles
  with_items: '{{ root_castles }}'
  when: root_castles|default(None) != None
  command: /root/.homesick/repos/homeshick/bin/homeshick -f -b -q link {{ item | basename }}
  changed_when: False
  tags:
    - root

- name: write sshkeys
  when: root_sshkeys|default(None) != None
  authorized_key:
    user: root
    key: '{{ root_sshkeys }}'
    path: /root/.ssh/authorized_keys
    exclusive: yes
    state: present
  tags:
    - root
